import Head from 'next/head'
import { ConnectButton } from '@rainbow-me/rainbowkit';
import { abi, WHITELIST_CONTRACT_ADDRESS }from "../constants"
import { useState, useEffect } from 'react';
import { useContractRead } from 'wagmi'
import { useContract } from 'wagmi';
import { useAccount, useConnect } from 'wagmi';
import { useProvider, useSigner } from 'wagmi';
import styles from '../styles/Home.module.css'

export default function Home() {
  const [join, setJoin] = useState(false);
  const { isConnected } = useAccount()
  const { connectors, connect } = useConnect();
  const { data: signer, isError, isLoading } = useSigner()
  const provider = useProvider()

  const contract = useContract ({
    addressOrName: WHITELIST_CONTRACT_ADDRESS,
    contractInterface: abi,
    signerOrProvider: signer, provider
  })

  const joinWhitelist = async () => {
    try {
      const tx = await contract.addAddressToWhitelist();
      await tx.wait();
      window.alert("WHITELIST SUCCESSFUL")
      setJoin(true)
    }catch(err){
      console.error(err)
    }
  }

  const {data} = useContractRead({
    addressOrName: WHITELIST_CONTRACT_ADDRESS,
    contractInterface: abi,
    functionName: 'numAddressesWhitelisted',
    onSuccess(data) {
      console.log('Success', data)
    },
  })


  return (
    <div className={styles.container}>
      <Head>
        <title>Rainbow Kit Wallet test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.navbar}>
            <div className={styles.navbarTitle}>
              <h1>RainbowKit test</h1>
            </div>
            {<ConnectButton chainStatus= {{
              smallScreen:"icon",
              largeScreen:"full"
            }} 
            
            accountStatus={{
              smallScreen: "avatar",
              largeScreen: "full"
            }}

            showBalance = {{
              smallScreen: "false",
              largeScreen: "true"
            }}
            
            />}
        </div>
        <div className={styles.main}>
          <div className={styles.button}>
          <button onClick={joinWhitelist}>Join Whitelist</button>
          <h2>{data} / 8 </h2>
          </div>
        </div>
    </div>
  )
}
